/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Livro;

/**
 *
 * @author John Peter
 */
public class FormConsultaLivro extends javax.swing.JFrame {
    
    public Livro livBuscar;
    
    /**
     * Creates new form FormConsultaLivro
     */
    public FormConsultaLivro() {        
        this.livBuscar = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbBuscarTodos = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jbBuscarLivro = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaConsulta = new javax.swing.JTextArea();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableLivo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Livro em Acervo");
        setResizable(false);

        jcbBuscarTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbBuscarTodos.setText("Buscar Todos");
        jcbBuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBuscarTodosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código:");

        jbBuscarLivro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbBuscarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones 72 x 72/StuffIt-Archive-Search-icon.png"))); // NOI18N
        jbBuscarLivro.setText("Buscar Livro");
        jbBuscarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarLivroActionPerformed(evt);
            }
        });

        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyTyped(evt);
            }
        });

        jtaConsulta.setColumns(20);
        jtaConsulta.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jtaConsulta.setRows(5);
        jScrollPane1.setViewportView(jtaConsulta);

        jbEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones 72 x 72/edit-file-icon.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones 72 x 72/trash-blue-empty-icon.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones 72 x 72/Actions-go-next-icon.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));

        jtableLivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Fornecedor", "Valor Un.", "Quant.", "Data Publicação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableLivo.setToolTipText("");
        jtableLivo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtableLivo.setCellSelectionEnabled(true);
        jtableLivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtableLivo.setDoubleBuffered(true);
        jtableLivo.setDragEnabled(true);
        jtableLivo.setGridColor(new java.awt.Color(0, 0, 0));
        jtableLivo.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jtableLivo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtableLivo.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtableLivo);
        jtableLivo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtableLivo.getColumnModel().getColumnCount() > 0) {
            jtableLivo.getColumnModel().getColumn(0).setResizable(false);
            jtableLivo.getColumnModel().getColumn(0).setPreferredWidth(60);
            jtableLivo.getColumnModel().getColumn(1).setResizable(false);
            jtableLivo.getColumnModel().getColumn(1).setPreferredWidth(90);
            jtableLivo.getColumnModel().getColumn(2).setResizable(false);
            jtableLivo.getColumnModel().getColumn(2).setPreferredWidth(90);
            jtableLivo.getColumnModel().getColumn(3).setResizable(false);
            jtableLivo.getColumnModel().getColumn(3).setPreferredWidth(60);
            jtableLivo.getColumnModel().getColumn(4).setResizable(false);
            jtableLivo.getColumnModel().getColumn(4).setPreferredWidth(60);
            jtableLivo.getColumnModel().getColumn(5).setResizable(false);
            jtableLivo.getColumnModel().getColumn(5).setPreferredWidth(100);
        }
        jtableLivo.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbEditar)
                        .addGap(34, 34, 34)
                        .addComponent(jbExcluir)
                        .addGap(37, 37, 37)
                        .addComponent(jbSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jbBuscarLivro)
                        .addGap(30, 30, 30)
                        .addComponent(jcbBuscarTodos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBuscarLivro)
                        .addComponent(jcbBuscarTodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSair)
                    .addComponent(jbExcluir)
                    .addComponent(jbEditar))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(857, 784));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        new FormLivro().setVisible(true);
        FormLivro.setLivBuscar(livBuscar);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbBuscarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarLivroActionPerformed
        if(!jcbBuscarTodos.isSelected()){            
            if( jtfCodigo.getText().trim().equals("") ){
                JOptionPane.showMessageDialog(null, "Preeencha corretamente o código", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }else{
                int codigo = Integer.parseInt(jtfCodigo.getText());
                livBuscar = FormPrincipal.bdLivro.buscarLivro( codigo );
                if(livBuscar != null){
                    jtaConsulta.setText(livBuscar.toString() );                    
                    preencherTabelaUnicoValor();                    
                    jbEditar.setEnabled(true); 
                    jbExcluir.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Livro não foi encontrado", "Aviso", JOptionPane.WARNING_MESSAGE);
                    jtaConsulta.setText("");
                    jtfCodigo.setText("");
                    desabilitarBotoes();
                    jtfCodigo.requestFocus();
                }        
            } 
        }else{
            if(FormPrincipal.bdLivro.todosLivros().isEmpty()){
                JOptionPane.showMessageDialog(null, "Lista de Livros se encontra vazia");
            }else{
                preencherTabelaMultiplosValores();                
                jtaConsulta.setText( FormPrincipal.bdLivro.todosLivros().toString() );
                desabilitarBotoes();
            }
        }
    }//GEN-LAST:event_jbBuscarLivroActionPerformed

    public void preencherTabelaMultiplosValores() {
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel modelo = (DefaultTableModel) jtableLivo.getModel();
        String data;
        limparTabela(modelo);
        for(int i = 0; i < FormPrincipal.bdLivro.todosLivros().size(); i++){            
            data = f.format( FormPrincipal.bdLivro.todosLivros().get(i).getData() );
            modelo.addRow(new Object[] { 
                FormPrincipal.bdLivro.todosLivros().get(i).getCodigo(),
                FormPrincipal.bdLivro.todosLivros().get(i).getTitulo(),
                FormPrincipal.bdLivro.todosLivros().get(i).getFornecedor(),
                FormPrincipal.bdLivro.todosLivros().get(i).getValorUnitario(),
                FormPrincipal.bdLivro.todosLivros().get(i).getQuantidade(),
                data
            });
        }
    }

    private void limparTabela(DefaultTableModel modelo) {
        for (int i = jtableLivo.getRowCount() - 1; i >= 0; --i){
            modelo.removeRow(i);
        }
    }

    private void preencherTabelaUnicoValor() {
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        String data = f.format( livBuscar.getData() );
        DefaultTableModel modelo = (DefaultTableModel) jtableLivo.getModel();
        limparTabela(modelo);
        modelo.addRow(new Object[] { livBuscar.getCodigo(), livBuscar.getTitulo(),
            livBuscar.getFornecedor(), livBuscar.getValorUnitario(), livBuscar.getQuantidade(),
            data});
    }

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        Object[] options = {"Sim", "Não"}; 
        int decisao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir?", "ATENÇÃO", 
        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]); 
        
        if (decisao == JOptionPane.YES_OPTION){
            jtfCodigo.setText("");
            jtaConsulta.setText("");
            desabilitarBotoes();
            FormPrincipal.bdLivro.removerLivro(livBuscar);            
        }
        jtfCodigo.requestFocus();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jcbBuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBuscarTodosActionPerformed
        if(jcbBuscarTodos.isSelected()){
            jtfCodigo.setText("");
            jtfCodigo.setEditable(false);
            jtfCodigo.setBackground(Color.gray);
        }else{
            jtfCodigo.setEditable(true);
            jtfCodigo.setBackground(Color.white);            
        }
    }//GEN-LAST:event_jcbBuscarTodosActionPerformed

    private void jtfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyTyped
        String caracteres = "0987654321";
        
        if(!caracteres.contains(evt.getKeyChar() + ""))
            evt.consume();
    }//GEN-LAST:event_jtfCodigoKeyTyped

    private void desabilitarBotoes() {
        jbExcluir.setEnabled(false);
        jbEditar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultaLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbBuscarLivro;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbSair;
    private javax.swing.JCheckBox jcbBuscarTodos;
    private javax.swing.JTextArea jtaConsulta;
    private javax.swing.JTable jtableLivo;
    private javax.swing.JTextField jtfCodigo;
    // End of variables declaration//GEN-END:variables
}
