/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JOptionPane;

/**
 *
 * @author Posto Figueira
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuICliente = new javax.swing.JMenuItem();
        jMenuIProduto = new javax.swing.JMenuItem();
        jMenuCompras = new javax.swing.JMenu();
        jMenuIDia = new javax.swing.JMenuItem();
        jMenuIMes = new javax.swing.JMenuItem();
        jMenuIAno = new javax.swing.JMenuItem();
        jMenuVenda = new javax.swing.JMenu();
        jMenuINovaVenda = new javax.swing.JMenuItem();
        jMenuIEmitir = new javax.swing.JMenuItem();
        jMenuSuporte = new javax.swing.JMenu();
        jMenuIAjuda = new javax.swing.JMenuItem();
        jMenuISuporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle da Livraria Livro Aberto");
        setExtendedState(6);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuCadastro.setText("Cadastro");

        jMenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuCliente.setText("Cliente");
        jMenuCadastro.add(jMenuCliente);

        jMenuProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuProduto.setText("Produto");
        jMenuCadastro.add(jMenuProduto);
        jMenuCadastro.add(jSeparator1);

        jMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuSair);

        jMenuBar1.add(jMenuCadastro);

        jMenuConsulta.setText("Consulta");

        jMenuICliente.setText("Clientes");
        jMenuConsulta.add(jMenuICliente);

        jMenuIProduto.setText("Produtos");
        jMenuConsulta.add(jMenuIProduto);

        jMenuCompras.setText("Compras");

        jMenuIDia.setText("Dia");
        jMenuCompras.add(jMenuIDia);

        jMenuIMes.setText("Mês");
        jMenuCompras.add(jMenuIMes);

        jMenuIAno.setText("Ano");
        jMenuCompras.add(jMenuIAno);

        jMenuConsulta.add(jMenuCompras);

        jMenuBar1.add(jMenuConsulta);

        jMenuVenda.setText("Vendas");

        jMenuINovaVenda.setText("Nova Venda");
        jMenuVenda.add(jMenuINovaVenda);

        jMenuIEmitir.setText("Emitir Nota Fiscal");
        jMenuVenda.add(jMenuIEmitir);

        jMenuBar1.add(jMenuVenda);

        jMenuSuporte.setText("Suporte");

        jMenuIAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuIAjuda.setText("Ajuda");
        jMenuSuporte.add(jMenuIAjuda);

        jMenuISuporte.setText("Suporte");
        jMenuSuporte.add(jMenuISuporte);

        jMenuBar1.add(jMenuSuporte);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(680, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        Object[] options = {"Sim", "Não"}; 
        int decisao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja sair?", "ATENÇÃO", 
        JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]); 
        if (decisao == JOptionPane.YES_OPTION) this.dispose();
    }//GEN-LAST:event_jMenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenu jMenuCompras;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenuItem jMenuIAjuda;
    private javax.swing.JMenuItem jMenuIAno;
    private javax.swing.JMenuItem jMenuICliente;
    private javax.swing.JMenuItem jMenuIDia;
    private javax.swing.JMenuItem jMenuIEmitir;
    private javax.swing.JMenuItem jMenuIMes;
    private javax.swing.JMenuItem jMenuINovaVenda;
    private javax.swing.JMenuItem jMenuIProduto;
    private javax.swing.JMenuItem jMenuISuporte;
    private javax.swing.JMenuItem jMenuProduto;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenu jMenuSuporte;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
